### ISSUE TITLE
Converting notes from midi file to pattern.  ?

### ISSUE THREAD

**Issue by CIRCE-EYES** [melanchall/drywetmidi#313] opened 2024-11-10 20:19 UTC
Hello everyone, this is a very very basic example of using the patternbuilder of this wonderful Drywet library, it is an example in vb.net, but I have a question, and that is that I have created a function to convert a midi file into a pattern, but It converts it note by note, that is, monophonic, would anyone know, even if it were in C#, how to convert a midi file into a pattern?
Thanks a lot

[Patterns.zip](https://github.com/user-attachments/files/17692923/Patterns.zip)

Try it please !!!!

![screenshot](https://github.com/user-attachments/assets/c7d7cacf-27af-42c9-b51c-e558d45e30f4)

**Comment by melanchall** [comment] 2024-11-11 15:42
Hi @CIRCE-EYES,

Well, in general, it's impossible to convert a MIDI file into a pattern since there is no direct matching between these two concepts. Pattern API is a subset of MIDI file API. So there are some things in a MIDI file that don't have corresponding things in a pattern.

And yes, pattern implies single channel for the entire pattern. There is no way to have multiple channels in one pattern.

Can you please say why do you need to transform a MIDI file into a pattern?

**Comment by CIRCE-EYES** [comment] 2024-11-11 17:05
Hello, as you can see it is not impossible to convert the midi file to pattern, I have managed to do it, although it sounds monophonically, maybe I can do it...... I am discovering the great potential that both the pattern and pianoroll functions have, I am doing tests and the conversion and manipulation of the patterns can be very fast AS LONG AS no more parameters are sent in the conversion, such as speed, length, triplet, whole, you know...just the notes and that's it, see for yourself in the example I have attached on your GitHub page. If midi sequences could be exported and imported in a .txt file, it would be a great advance in the manipulation of patterns without depending on midi files. Believe me, it is worth trying to transcribe midi files into patterns... Thank you very much, anyway I am going to continue working on those conversions, if you think you can solve it, DO NOT HESITATE to write to me, I think there is great potential in paterns, although their use seems somewhat hidden......

**Comment by CIRCE-EYES** [comment] 2024-11-11 17:11
_**And yes, pattern implies single channel for the entire pattern. There is no way to have multiple channels in one pattern**_.....

Yes, but It doesnt Matter one Channel only, the main issue is to convert It into poliphonic notes

**Comment by CIRCE-EYES** [comment] 2024-11-11 19:33
Almost get the conversion from midifile to pattern, to check it I resave in midifile again, now it converts to poliphonic, but only the first notes !!!!!!


```
private void Button11_Click_1(object sender, EventArgs e)
{
    var midiFile = MidiFile.Read("Katia.mid");

    // Create a new PatternBuilder
    var patternBuilder = new PatternBuilder();

    // Process events from the first track of the MIDI file
    var trackChunk = midiFile.GetTrackChunks().FirstOrDefault();
    if (trackChunk != null)
    {
        // Find all NoteOn events
        var noteOnEvents = trackChunk.Events.OfType<NoteOnEvent>();
        var noteOffEvents = trackChunk.Events.OfType<NoteOffEvent>();

        // Create a list to group notes that should sound at the same time
        var groupedNotes = noteOnEvents.GroupBy(note => note.DeltaTime);

        foreach (var group in groupedNotes)
        {
            // Get the minimum duration for the notes in this group
            var notesWithDurations = noteOnEvents.Select(noteOn => new
            {
                Note = noteOn,
                Duration = noteOffEvents
                    .Where(noteOff => (int)noteOff.NoteNumber == (int)noteOn.NoteNumber && noteOff.DeltaTime >= noteOn.DeltaTime)
                    .Select(noteOff => noteOff.DeltaTime - noteOn.DeltaTime)
                    .DefaultIfEmpty(0) // Provide a default value if there are no matches
                    .FirstOrDefault()
            }).ToList();

            // Get the shortest duration in the group
            var shortestDuration = notesWithDurations.Min(n => n.Duration);
            var noteLength = shortestDuration > 0 ? TimeConverter.ConvertTo<MusicalTimeSpan>(shortestDuration, midiFile.GetTempoMap()) : MusicalTimeSpan.Quarter;

            // Add notes as a chord if there are more than one
            var chordNotes = notesWithDurations.Select(n => n.Note.GetNoteName()).ToArray();
            if (chordNotes.Length > 1)
            {
                patternBuilder.Chord(chordNotes, noteLength);
            }
            else
            {
                // Add a single note if there is no chord
                patternBuilder.Note(chordNotes[0], noteLength, notesWithDurations.First().Note.Velocity);
            }
        }
    }

    // Build the pattern
    var pattern = patternBuilder.Build();

    // Convert the pattern to a new MIDI file
    var midiFile2 = pattern.ToFile(TempoMap.Create(Tempo.FromBeatsPerMinute(80)));
    midiFile2.Write("exportkatia.mid", true);
    
    _playback = midiFile2.GetPlayback(_outputDevice);
    _playback.Start();
}
```

**Comment by CIRCE-EYES** [comment] 2024-11-11 19:48
Uffff... I think I've made a mess with notes and chords...

**Comment by melanchall** [comment] 2024-11-12 17:21
As I've said:

> Pattern API is a subset of MIDI file API. So there are some things in a MIDI file that don't have corresponding things in a pattern.

And looking into your code I can say that you ignore pretty much things that can exist in a MIDI file. For example, markers. Proper name of your task is not "convert a MIDI file into a pattern", but "convert notes into a pattern". And that's definitely possible.

Also why do you collect Note On and Note Off events and then do those big calculations? You can just get all notes in a file with `midiFile.GetNotes`.

Also this obviously wrong:

```csharp
noteOnEvents.GroupBy(note => note.DeltaTime);
```

I suppose you think DeltaTIme is the absolute time of an event, but that's wrong. Grouping by delta-times is useless and that's what drives your algorithm crazy I think.

**Comment by CIRCE-EYES** [comment] 2024-11-12 19:00
Hi Max, thanks again, as I said before, the function of converting file to pattern is something I'm just starting to discover, it's only been 5 days since I tried it, so I'm still testing to make sure it's correct. conversion. You have written that if the statement were notes to pattern that would be different... and the truth is that I was very happy, because it seems then that the conversion could be done using midifile.Getfiles. I keep testing and I can't get it... and it makes me very angry, because I see that the use of patterns within the code is very useful, I know you're wondering why convert a midi file to a pattern if I already have it available... The answer is that the patterns could be embedded within the source code and be modified through some graphical interface, either a grid or a multiline text box, so notes and durations could be modified without having to do so using the midi file. . I'll give you an example...imagine a form full of buttons that were rhythm patterns, and other windows that were bass lines, and other windows that were chords, because the possibilities of using those patterns would be interesting with a view to playing simple songs. ...this is all an example of course. Here comes a request for you... could you help me create that function that loads the notes from the file and converts them to pattern? I know that it wouldn't take much effort for you because you know what's under the hood of your library.!! Thank you very much again!!!

**Comment by CIRCE-EYES** [comment] 2024-11-13 09:43
I have simplified the code, and still get a **pattern monophonic** file....

```
private void Button3_Click(object sender, EventArgs e)
{
    MidiFile midiFile = MidiFile.Read("Katia.mid");
    TempoMap tempoMap = midiFile.GetTempoMap();
    IEnumerable<Note> notes = midiFile.GetNotes();

    // Create a PatternBuilder
    PatternBuilder patternBuilder = new PatternBuilder();

    // Add notes to the PatternBuilder
    foreach (Note note in notes)
    {
        // Convert the note's start time
        MetricTimeSpan startTime = TimeConverter.ConvertTo<MetricTimeSpan>(note.Time, tempoMap);

        // Set the length of the note (this depends on how you want to represent it)
        MusicalTimeSpan noteLength = MusicalTimeSpan.Quarter;  // You can change the duration as needed

        // Add the note to the pattern with the desired duration
        patternBuilder.Note(note.NoteName, noteLength);
    }

    // Create the Pattern
    Pattern pattern = patternBuilder.Build();

    MidiFile midiFile2 = pattern.ToFile(TempoMap.Default);
   
    // Play the resulting MIDI file
    _playback = midiFile2.GetPlayback(_outputDevice);
    _playback.Start();
}
```

A tiny help would be great !!

**Comment by melanchall** [comment] 2024-11-14 14:01
Please take a look on this code:

```csharp
// Move the PatternBuilder "cursor" to the start time of the group
patternBuilder.AnchorTo(startTime);

// Add each note in the group to the pattern in parallel to form chords
foreach (var note in noteGroup)
{
    MusicalTimeSpan noteLength = LengthConverter.ConvertTo<MusicalTimeSpan>(note.Length, tempoMap);
    patternBuilder.Note(note.NoteName, noteLength);
}
```

So what's happening here?

1. You move the pointer to the `startTime` (I don't know what `AnchorTo` is, but I suppose it's just `MoveToTime` call).
2. You insert first note of the group.
3. **After previous `Note` call the pointer will be moved by the `PatternBuilder` by `noteLength` step**.
4. So the second note will be inserted **after** first one.

I suppose you forgot about behavior described in point 3. But there is my fault here too. I didn't specify that in the documentation. So I'll fix the docs.

As for the code above, try to change it to:

```csharp
// Add each note in the group to the pattern in parallel to form chords
foreach (var note in noteGroup)
{
    // Move the PatternBuilder "cursor" to the start time of the group
    patternBuilder.AnchorTo(startTime);

    MusicalTimeSpan noteLength = LengthConverter.ConvertTo<MusicalTimeSpan>(note.Length, tempoMap);
    patternBuilder.Note(note.NoteName, noteLength);
}
```

**Comment by CIRCE-EYES** [comment] 2024-11-14 19:14
Fixed !

This is ne complet function to convert any midi file to pattern, any way there is a possible bug?
I mean if the midi file contains note very high appears a bug....
I post the executable to you can try it, as soon is fixed I will post here reconverted in CSharp code.

Thanks a lot Maxim.


```
private void Button3_Click(object sender, EventArgs e)
{
    MidiFile midiFile = MidiFile.Read("Comic.mid");
    TempoMap tempoMap = midiFile.GetTempoMap();
    IEnumerable<Note> notes = midiFile.GetNotes();

    PatternBuilder patternBuilder = new PatternBuilder();

    var groupedNotes = notes.GroupBy(n => n.Time);

    foreach (var noteGroup in groupedNotes)
    {
        MetricTimeSpan startTime = TimeConverter.ConvertTo<MetricTimeSpan>(noteGroup.Key, tempoMap);

        patternBuilder.MoveToTime(startTime);

        foreach (var note in noteGroup)
        {
            patternBuilder.MoveToTime(startTime);
            MusicalTimeSpan noteLength = TimeConverter.ConvertTo<MusicalTimeSpan>(note.Length, tempoMap);
            patternBuilder.Note(note.NoteNumber, noteLength);
        }
    }

    Pattern pattern = patternBuilder.Build();
    MidiFile midiFile2 = pattern.ToFile(TempoMap.Default);
    int transposeBy = -60;
    midiFile2.ProcessNotes(n => n.NoteNumber = (SevenBitNumber)((int)n.NoteNumber + transposeBy), n => (int)n.Channel != 9);
    midiFile2.Write("Export_Comic.mid", true);

    _playback = midiFile2.GetPlayback(_outputDevice);
    _playback.Start();
}
```


In this sentence appears give me the bug about value =  patternBuilder.Note(note.NoteNumber, **noteLength**);


a screenshot 👍 
![screenshot bug](https://github.com/user-attachments/assets/278f453c-cdad-4b4f-9c46-3450bda582c3)


Here is the whole code 👍 
[Patterns_2.zip](https://github.com/user-attachments/files/17756640/Patterns_2.zip)

**Comment by CIRCE-EYES** [comment] 2024-11-16 17:21
Your solution is good If  I convert the file to midi....

 But it appears before the conversion ! So the bug is in the function: patternBuilder.Note(note.NoteNumber, noteLength); // <----- Here is where marks the bug!!

So I quit the function to export midifile... 



private void Button3_Click(object sender, EventArgs e)
{
    MidiFile midiFile = MidiFile.Read("Comic.mid");
    TempoMap tempoMap = midiFile.GetTempoMap();
    IEnumerable<Note> notes = midiFile.GetNotes();

    PatternBuilder patternBuilder = new PatternBuilder();
    var groupedNotes = notes.GroupBy(n => n.Time);

    foreach (var noteGroup in groupedNotes)
    {
        MetricTimeSpan startTime = TimeConverter.ConvertTo<MetricTimeSpan>(noteGroup.Key, tempoMap);

        foreach (var note in noteGroup)
        {
            patternBuilder.MoveToTime(startTime);
            MusicalTimeSpan noteLength = TimeConverter.ConvertTo<MusicalTimeSpan>(note.Length, tempoMap);
            patternBuilder.Note(note.NoteNumber, noteLength); // <----- Here its where marks the bug !!
        }
    }
}

**Comment by melanchall** [comment] 2024-11-17 10:11
> patternBuilder.Note(note.NoteNumber, noteLength);

No, the bug is not here. It's where I've shown before:

> n.NoteNumber = (SevenBitNumber)((int)n.NoteNumber + transposeBy)

Why did you decide the problem is with `patternBuilder.Note`? Do you use debugger in Visual Studio (you need to run your app from VS in Debug mode)? In the debugger you will be directed right on the line with the issue. Show me please a screenshot in debugger with the error reported.

**Comment by CIRCE-EYES** [comment] 2024-11-17 14:41
Hello Max, in order to explain myself better, I have converted all my vbnet code to Csharp, so you can better see my concerns and questions.

As you will see, I have posted both the entire source code and the application.
You could run it and check that I'm not saying anything strange...

I have posted three screenshots using the debugger, in all of them it tells us that the value is out of range. but the most curious thing is that I have removed the function of exporting the file to MIDI, therefore the bug is in the conversion of the file because it reads it (I think) with 5 octaves of difference, that's why I have to transfer the final value to -60.

When you say that the error is in the transposition of the note, now in theory it should not appear, since I have removed the export function that used the transposed value.

![Debug 1](https://github.com/user-attachments/assets/7459a971-0784-447c-939b-2c03bf0b4069)
![Debug 2](https://github.com/user-attachments/assets/50dc10f1-a084-4fe7-b859-8cb5d00ac5e9)
![Debug 3](https://github.com/user-attachments/assets/963392f1-27c7-43a7-9f21-0fb11734e0d9)

[Mini_colors In Csharp.zip](https://github.com/user-attachments/files/17790917/Mini_colors.In.Csharp.zip)

**Comment by melanchall** [comment] 2024-11-18 08:32
Thank you for the solution! I found the issue. This instruction

```csharp
patternBuilder.Note(note.NoteNumber, noteLength);
```

treats `note.NoteNumber` as the `Interval` (because there is no `Note` method accepting `SevenBitNumber`) causing transposing internally. The fix is simple:

```csharp
```

**Comment by CIRCE-EYES** [comment] 2024-11-18 22:13
THANK YOU SO MUCH AGAIN!!!! Maxim

I'm glad that the solution was easy to solve.

Everything works well, the conversion is done on the fly, it is very fast, not only the conversion but also the new reading of the file, I mean super fast!!!

Now that it is possible to import midi files....

Now I am going to continue researching pattern manipulation.

**Closed** 2024-11-18 22:23 UTC
Labels: question
