### ISSUE TITLE
DllNotFoundException: Melanchall_DryWetMidi_Native64 in Unity

### ISSUE THREAD

**Issue by BoxOfClicks** [melanchall/drywetmidi#140] opened 2021-10-25 12:05 UTC
Apologies if I'm missing something basic but after importing DWM into a Unity project I'm receiving the following error.
I wonder if it's something to do with the recent changes to e.g. CommonApi?
Any thoughts or ideas I could test are much appreciated.

**Comment by melanchall** [comment] 2021-11-01 15:23
I've added [Using in Unity](https://melanchall.github.io/drywetmidi/articles/dev/Using-in-Unity.html) article which shows example of simple script with devices. Please see how they should be obtained and disposed. I've tested the script within Unity and all works fine.

@BoxOfClicks I'm closing the issue since there is no info from you. Feel free to reopen if you can provide sample project which can reproduce your problem.

**Closed** 2021-11-01 15:24 UTC
Labels: question, unity

**Comment by schuster-rainer** [comment] 2021-12-29 23:05
I'm using it in Visual Scripting in a custom unit. and get the same exception, albeit I'm not using any output device. Is this intended?

```csharp
using Unity.VisualScripting;
using UnityEngine;
using Melanchall.DryWetMidi.Core;
using Melanchall.DryWetMidi.Interaction;
using System;
using Melanchall.DryWetMidi.Multimedia;



public class MidiPlayer : Unit
{
    [DoNotSerialize]
    public ValueInput fileNameInput;
    [DoNotSerialize]
    public ControlInput inputTrigger;

    [DoNotSerialize]
    public ControlInput playTrigger;

    [DoNotSerialize]
    public ControlOutput outputTrigger;

    [DoNotSerialize]
    public ControlOutput noteTrigger;

    [DoNotSerialize]
    public ValueOutput notesCountOutput;

    [DoNotSerialize]
    public ValueOutput noteOutput;

    [DoNotSerialize]
    private MidiFile midiFile;

    [DoNotSerialize]
    private NotePlaybackData currentNote;

    private Playback playback;


    protected override void Definition()
    {

        inputTrigger = ControlInput("", (flow) =>
        {
            var file = flow.GetValue<string>(fileNameInput);
            midiFile = MidiFile.Read(Application.streamingAssetsPath + "/" + file);
            //resultValue = flow.GetValue<string>(myValueA) + flow.GetValue<string>(myValueB) + "!!!";
            return outputTrigger;
        });

        playTrigger = ControlInput("play", (flow) =>
        {
            //if (midiFile == null) return noteTrigger;

            playback = midiFile.GetPlayback();

            playback.NoteCallback += delegate (NotePlaybackData rawNoteData, long rawTime, long rawLength, TimeSpan playbackTime)
                {
                    currentNote = rawNoteData;
                    return rawNoteData;
                };
            try
            {
                playback.Start();
            }
            catch (Exception ex)
            {
                Debug.LogWarning(ex);
            }
            
            return noteTrigger;
        });

        outputTrigger = ControlOutput("");
        noteTrigger = ControlOutput("note played");
        fileNameInput = ValueInput<string>("fileName", string.Empty);
        notesCountOutput = ValueOutput<int>("notes count", (flow) => {
            var notes = midiFile.GetNotes();
            return notes.Count;
        });
        noteOutput = ValueOutput<NotePlaybackData>("current note", (flow) => {
            return currentNote;
        });


        //We need fileName to be set to let the unit process
        Requirement(fileNameInput, inputTrigger); 
        //Requirement(myValueB, inputTrigger); //To display that we need the myValueB value to be set to let the unit process
        Succession(inputTrigger, outputTrigger); //To display that the input trigger port input will exits at the output trigger port exit. Not setting your succession also grays out the connected nodes but the execution is still done.
        Succession(playTrigger, noteTrigger);
        Assignment(playTrigger, noteOutput);
        Assignment(inputTrigger, notesCountOutput);//To display the data that is written when the inputTrigger is triggered to the result string output.
    }

    protected override void BeforeUndefine()
    {
        base.BeforeUndefine();
        playback.NoteCallback = null;
        playback.Dispose();

    }
}
```

**Comment by melanchall** [comment] 2021-12-30 10:47
Hi @schuster-rainer,

> Is this intended?

Yes, because you use `Playback` class. By default it uses `HighPrecisionTickGenerator` (you can read more [here](https://melanchall.github.io/drywetmidi/articles/playback/Tick-generator.html)). It's a timer that can fire at interval of 1 ms. Such high-precision timer is platform-dependent and thus it is implemented via native layer provided by _Melanchall_DryWetMidi_Native64.dll_ (_.dylib_) file. So you just need to follow the [instruction](https://melanchall.github.io/drywetmidi/articles/dev/Using-in-Unity.html) (please see point 3 in the list there).

Of course you can override default behavior and use your [own tick generator](https://melanchall.github.io/drywetmidi/articles/playback/Tick-generator.html#custom-tick-generator) implementation. In this case it will be up to you how to implement it, native libraries of DryWetMIDI won't be required. But DryWetMIDI tries to provide the best implementation (in terms of CPU and power usage) for each supported platform (right now, high-precision tick generator supported on Windows and macOS).
